

import Database.Settings;
import Edit.addUserIF;
import Edit.deleteUserIF;
import Help.aboutIF;
import Help.infoIF;
import Report.dailyReportIF;
import Report.monthlyReportIF;
import Report.stockReportIF;
import StockEntry.addProductInternalFrame;
import StockEntry.deleteProductIF;
import StockEntry.updateProductIF;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import sun.awt.WindowClosingListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminMenuForm.java
 *
 * Created on Jun 12, 2012, 11:42:35 PM
 */
/**
 *
 * @author Sayed Mahmud Reza
 */
public class AdminMenuForm extends javax.swing.JFrame{

    /** Creates new form AdminMenuForm */
    public AdminMenuForm() {
        initComponents();
        this.setSize(Settings.getScreenSize().width, Settings.getScreenSize().height - 30);
  this.setIconImage(new ImageIcon(ClassLoader.getSystemResource("images/company_logo.jpg")).getImage());
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        addUserMenuItem = new javax.swing.JMenuItem();
        deleteUserMenuItem = new javax.swing.JMenuItem();
        backHomeMenuItem = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        backMenuItem = new javax.swing.JMenuItem();
        addProductMenu = new javax.swing.JMenu();
        addProductMenuItem = new javax.swing.JMenuItem();
        updateProductMI = new javax.swing.JMenuItem();
        deleteProductMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        stockReportMenuItem = new javax.swing.JMenuItem();
        dailyReportMenuItem = new javax.swing.JMenuItem();
        monthlyReportMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        calculatorMenuItem = new javax.swing.JMenuItem();
        notePadMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        infoMI = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mailToMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proshanti Computer Ltd.");

        DesktopPane.setBackground(new java.awt.Color(204, 204, 255));

        jToolBar2.setRollover(true);
        jToolBar2.setBounds(0, 0, 1240, 40);
        DesktopPane.add(jToolBar2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel1.setText("Product Version: Shop Management System 7.0 (Build 2013-03-28) Platform: Java: 1.6.0_10; Java HotSpot(TM) Client VM 11.0-b15 System: Windows Vista version 6.1 running on x86; Cp1252; en_US (nb) Database file: reza.accdb");
        jToolBar1.add(jLabel1);

        fileMenu.setText("File");

        addUserMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addUserMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/newreg.png"))); // NOI18N
        addUserMenuItem.setText("Add User");
        addUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(addUserMenuItem);

        deleteUserMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        deleteUserMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delreg.png"))); // NOI18N
        deleteUserMenuItem.setText("Delete User");
        deleteUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(deleteUserMenuItem);

        backHomeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        backHomeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backover.jpg"))); // NOI18N
        backHomeMenuItem.setText("Back to Home Page");
        backHomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(backHomeMenuItem);

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK));
        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        logOutMenuItem.setText("Log Out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logOutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        jMenu1.setText("Edit");

        backMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        backMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backover.jpg"))); // NOI18N
        backMenuItem.setText("Back");
        backMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(backMenuItem);

        jMenuBar1.add(jMenu1);

        addProductMenu.setText("Stock Entry");

        addProductMenuItem.setText("Add Product");
        addProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductMenuItemActionPerformed(evt);
            }
        });
        addProductMenu.add(addProductMenuItem);

        updateProductMI.setText("Update Product");
        updateProductMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductMIActionPerformed(evt);
            }
        });
        addProductMenu.add(updateProductMI);

        deleteProductMI.setText("Delete Product");
        deleteProductMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductMIActionPerformed(evt);
            }
        });
        addProductMenu.add(deleteProductMI);

        jMenuBar1.add(addProductMenu);

        jMenu2.setText("Report ");

        stockReportMenuItem.setText("Stock Report");
        stockReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(stockReportMenuItem);

        dailyReportMenuItem.setText("Daily Report");
        dailyReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(dailyReportMenuItem);

        monthlyReportMenuItem.setText("Monthly Report");
        monthlyReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(monthlyReportMenuItem);

        jMenuBar1.add(jMenu2);

        toolsMenu.setText("Tools");

        calculatorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        calculatorMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calc.png"))); // NOI18N
        calculatorMenuItem.setText("Calculator");
        calculatorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(calculatorMenuItem);

        notePadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        notePadMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notepad.png"))); // NOI18N
        notePadMenuItem.setText("NotePad");
        notePadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notePadMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(notePadMenuItem);

        jMenuBar1.add(toolsMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editusr.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        infoMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        infoMI.setText("Information");
        infoMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMIActionPerformed(evt);
            }
        });
        helpMenu.add(infoMI);

        jMenuBar1.add(helpMenu);

        jMenu3.setText("Mail");

        mailToMenuItem.setText("Mail to...");
        mailToMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailToMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(mailToMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       // TODO add your handling code here:
        int value2 = JOptionPane.showConfirmDialog(null, "Are you sure to exit?", "Confirm Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(value2 == JOptionPane.YES_OPTION){
                System.exit(0); 
        }
        
            
}//GEN-LAST:event_exitMenuItemActionPerformed

    private void backMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuItemActionPerformed
        this.setVisible(false);
       logInF re = new logInF();
        re.setVisible(true);     // TODO add your handling code here:
}//GEN-LAST:event_backMenuItemActionPerformed

    private void calculatorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorMenuItemActionPerformed
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Have an error", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_calculatorMenuItemActionPerformed

    private void notePadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notePadMenuItemActionPerformed
        try {
            Runtime.getRuntime().exec("notepad.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Have an error", "Invalid", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
}//GEN-LAST:event_notePadMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        aboutIF aif = new aboutIF();
        DesktopPane.add(aif);
        
                aif.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_aboutMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
   int value2 = JOptionPane.showConfirmDialog(null, "Are you sure to log out?", "Confirm Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(value2 == JOptionPane.YES_OPTION){
         this.dispose();
        logInF w2 = new logInF();
        w2.setVisible(true);
              }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    private void addUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserMenuItemActionPerformed
      addUserIF au = new addUserIF();
      DesktopPane.add(au);
        

        au.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserMenuItemActionPerformed

    private void deleteUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserMenuItemActionPerformed
        deleteUserIF d1 = new deleteUserIF();
        DesktopPane.add(d1);
        
              
        d1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserMenuItemActionPerformed

    private void backHomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeMenuItemActionPerformed
        this.dispose();
        HomePage h2 = new HomePage();
        h2.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_backHomeMenuItemActionPerformed

    private void stockReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockReportMenuItemActionPerformed
//        this.setVisible(false);
//        AdminStockReportFrame adminStockreport = new AdminStockReportFrame();
//        adminStockreport.setVisible(true);



        // TODO add your handling code here:
        
//      stock_report sr = new stock_report();
//      
//        DesktopPane.add(sr);
//        sr.setVisible(true);
//        
      
        stockReportIF sr = new stockReportIF();
        DesktopPane.add(sr);
        sr.setVisible(true);
    }//GEN-LAST:event_stockReportMenuItemActionPerformed

    private void dailyReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReportMenuItemActionPerformed
//        this.dispose();
//        AdminDailyReportFrame adminDailyReport = new AdminDailyReportFrame();
//        adminDailyReport.setVisible(true);
        // TODO add your handling code here:
        
        dailyReportIF dr = new dailyReportIF();
        DesktopPane.add(dr);
        dr.setVisible(true);
        
    }//GEN-LAST:event_dailyReportMenuItemActionPerformed

    private void monthlyReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyReportMenuItemActionPerformed
      monthlyReportIF mr = new monthlyReportIF();
      DesktopPane.add(mr);
      mr.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_monthlyReportMenuItemActionPerformed

    private void mailToMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailToMenuItemActionPerformed
        // TODO add your handling code here:

        try {

            if ((new File("C:\\Documents and Settings\\Sayed Mahmud Reza\\My Documents\\NetBeansProjects\\SendEmailJavaDesktopExample\\dist\\SendEmailJavaDesktopExample.jar")).exists()) {

                Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler C:\\Documents and Settings\\Sayed Mahmud Reza\\My Documents\\NetBeansProjects\\SendEmailJavaDesktopExample\\dist\\SendEmailJavaDesktopExample.jar");
                p.waitFor();

            } else {

                JOptionPane.showMessageDialog(null, "File is not exists", "Error", JOptionPane.INFORMATION_MESSAGE);

            }


            //JOptionPane.showMessageDialog(null,"Successful","Success",JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_mailToMenuItemActionPerformed

    private void addProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductMenuItemActionPerformed
        // TODO add your handling code here:
        addProductInternalFrame apif = new addProductInternalFrame();
        DesktopPane.add(apif);
        apif.setVisible(true);



    }//GEN-LAST:event_addProductMenuItemActionPerformed

    private void updateProductMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductMIActionPerformed
        // TODO add your handling code here:
        updateProductIF up = new updateProductIF();
        DesktopPane.add(up);
        up.setVisible(true);
        
    }//GEN-LAST:event_updateProductMIActionPerformed

    private void deleteProductMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductMIActionPerformed
        // TODO add your handling code here:
        
        deleteProductIF dp = new deleteProductIF();
        DesktopPane.add(dp);
        dp.setVisible(true);
    }//GEN-LAST:event_deleteProductMIActionPerformed

    private void infoMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMIActionPerformed
        // TODO add your handling code here:
        infoIF ii = new infoIF();
        DesktopPane.add(ii);
        ii.setVisible(true);
        
        
    }//GEN-LAST:event_infoMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminMenuForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu addProductMenu;
    private javax.swing.JMenuItem addProductMenuItem;
    private javax.swing.JMenuItem addUserMenuItem;
    private javax.swing.JMenuItem backHomeMenuItem;
    private javax.swing.JMenuItem backMenuItem;
    private javax.swing.JMenuItem calculatorMenuItem;
    private javax.swing.JMenuItem dailyReportMenuItem;
    private javax.swing.JMenuItem deleteProductMI;
    private javax.swing.JMenuItem deleteUserMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem infoMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuItem mailToMenuItem;
    private javax.swing.JMenuItem monthlyReportMenuItem;
    private javax.swing.JMenuItem notePadMenuItem;
    private javax.swing.JMenuItem stockReportMenuItem;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JMenuItem updateProductMI;
    // End of variables declaration//GEN-END:variables

   
  
}
