
import Database.Settings;
import Help.aboutIF;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on May 23, 2012, 12:56:13 PM
 */
/**
 *
 * @author Sayed Mahmud Reza
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
         this.setSize(Settings.getScreenSize().width, Settings.getScreenSize().height - 30);
         this.setIconImage(new ImageIcon(ClassLoader.getSystemResource("images/company_logo.jpg")).getImage());
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        backHomeMenuItem = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        saleProductsMenuItem = new javax.swing.JMenuItem();
        returnSaleProductsMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        backMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        dailyReportMenuItem = new javax.swing.JMenuItem();
        monthlyReportMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        calculatorMenuItem = new javax.swing.JMenuItem();
        notePadMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proshanti Computer Ltd.");

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel1.setText("Product Version: Shop Management System 7.0 (Build 2013-03-28) Platform: Java: 1.6.0_10; Java HotSpot(TM) Client VM 11.0-b15 System: Windows Vista version 6.1 running on x86; Cp1252; en_US (nb) Database file: reza.accdb");
        jToolBar1.add(jLabel1);

        fileMenu.setText("File");

        backHomeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        backHomeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backover.jpg"))); // NOI18N
        backHomeMenuItem.setText("Back to Home Page");
        backHomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(backHomeMenuItem);

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK));
        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        logOutMenuItem.setText("Log Out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logOutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        jMenu3.setText("Purchase");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        saleProductsMenuItem.setText("Sale Products");
        saleProductsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleProductsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(saleProductsMenuItem);

        returnSaleProductsMenuItem.setText("Return Sale Products");
        returnSaleProductsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnSaleProductsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(returnSaleProductsMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Edit");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        backMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        backMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backover.jpg"))); // NOI18N
        backMenuItem.setText("Back");
        backMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(backMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        dailyReportMenuItem.setText("Daily Report");
        dailyReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(dailyReportMenuItem);

        monthlyReportMenuItem.setText("Monthly Report");
        monthlyReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(monthlyReportMenuItem);

        jMenuBar1.add(jMenu2);

        toolsMenu.setText("Tools");

        calculatorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        calculatorMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calc.png"))); // NOI18N
        calculatorMenuItem.setText("Calculator");
        calculatorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(calculatorMenuItem);

        notePadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        notePadMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notepad.png"))); // NOI18N
        notePadMenuItem.setText("NotePad");
        notePadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notePadMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(notePadMenuItem);

        jMenuBar1.add(toolsMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editusr.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_exitMenuItemActionPerformed

    private void backMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuItemActionPerformed
this.setVisible(false);
logInF re = new logInF();
        re.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
      // TODO add your handling code here:
         Help.aboutIF about = new aboutIF();
        jDesktopPane1.add(about);
        about.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void calculatorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorMenuItemActionPerformed
        try{
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Have an error","Invalid",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_calculatorMenuItemActionPerformed

    private void notePadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notePadMenuItemActionPerformed
        try{
            Runtime.getRuntime().exec("notepad.exe");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Have an error","Invalid",JOptionPane.ERROR_MESSAGE);
        }
        
        // TODO add your handling code here:
}//GEN-LAST:event_notePadMenuItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void backHomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeMenuItemActionPerformed
        this.dispose();
        HomePage h2 = new HomePage();
        h2.setVisible(true);
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_backHomeMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
        this.dispose();
        logInF w2 = new logInF();
        w2.setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_logOutMenuItemActionPerformed

    private void saleProductsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleProductsMenuItemActionPerformed
try{
        this.setVisible(false);
        saleProductFrame f1= new saleProductFrame();
f1.setVisible(true);
}catch(Exception e){
    JOptionPane.showMessageDialog(null, "Can't enter for any error", "Error", JOptionPane.INFORMATION_MESSAGE);
}        // TODO add your handling code here:
    }//GEN-LAST:event_saleProductsMenuItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void returnSaleProductsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnSaleProductsMenuItemActionPerformed

        this.setVisible(false);
returnSaleProductFrame f3 = new returnSaleProductFrame();
f3.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_returnSaleProductsMenuItemActionPerformed

    private void dailyReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReportMenuItemActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_dailyReportMenuItemActionPerformed

    private void monthlyReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyReportMenuItemActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_monthlyReportMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem backHomeMenuItem;
    private javax.swing.JMenuItem backMenuItem;
    private javax.swing.JMenuItem calculatorMenuItem;
    private javax.swing.JMenuItem dailyReportMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuItem monthlyReportMenuItem;
    private javax.swing.JMenuItem notePadMenuItem;
    private javax.swing.JMenuItem returnSaleProductsMenuItem;
    private javax.swing.JMenuItem saleProductsMenuItem;
    private javax.swing.JMenu toolsMenu;
    // End of variables declaration//GEN-END:variables
}
